# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import library_entities_pb2 as library__entities__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17inventory_service.proto\x12\tinventory\x1a\x16library_entities.proto\"P\n\x11\x43reateBookRequest\x12*\n\x0c\x62ookToCreate\x18\x01 \x01(\x0b\x32\x0f.inventory.BookH\x00\x88\x01\x01\x42\x0f\n\r_bookToCreate\"o\n\x12\x43reateBookResponse\x12\x13\n\x06result\x18\x01 \x01(\tH\x00\x88\x01\x01\x12.\n\x06status\x18\x02 \x01(\x0b\x32\x19.inventory.ResponseStatusH\x01\x88\x01\x01\x42\t\n\x07_resultB\t\n\x07_status\",\n\x0eGetBookRequest\x12\x11\n\x04isbn\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_isbn\"y\n\x0fGetBookResponse\x12\"\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0f.inventory.BookH\x00\x88\x01\x01\x12.\n\x06status\x18\x02 \x01(\x0b\x32\x19.inventory.ResponseStatusH\x01\x88\x01\x01\x42\x07\n\x05_bookB\t\n\x07_status2\x9f\x01\n\x10LibraryInventory\x12I\n\nCreateBook\x12\x1c.inventory.CreateBookRequest\x1a\x1d.inventory.CreateBookResponse\x12@\n\x07GetBook\x12\x19.inventory.GetBookRequest\x1a\x1a.inventory.GetBookResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEBOOKREQUEST._serialized_start=62
  _CREATEBOOKREQUEST._serialized_end=142
  _CREATEBOOKRESPONSE._serialized_start=144
  _CREATEBOOKRESPONSE._serialized_end=255
  _GETBOOKREQUEST._serialized_start=257
  _GETBOOKREQUEST._serialized_end=301
  _GETBOOKRESPONSE._serialized_start=303
  _GETBOOKRESPONSE._serialized_end=424
  _LIBRARYINVENTORY._serialized_start=427
  _LIBRARYINVENTORY._serialized_end=586
# @@protoc_insertion_point(module_scope)
