# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library_entities.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16library_entities.proto\x12\tinventory\x1a\x19google/protobuf/any.proto\"V\n\x0eResponseStatus\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12%\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32\x14.google.protobuf.Any\"\xa2\x02\n\x04\x42ook\x12\x11\n\x04isbn\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05title\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06\x61uthor\x18\x03 \x01(\tH\x02\x88\x01\x01\x12)\n\x05genre\x18\x04 \x01(\x0e\x32\x15.inventory.Book.GenreH\x03\x88\x01\x01\x12\x15\n\x08pub_year\x18\x05 \x01(\x05H\x04\x88\x01\x01\"g\n\x05Genre\x12\x14\n\x10\x46ICTION_THRILLER\x10\x00\x12\x14\n\x10\x46ICTION_ROMANTIC\x10\x01\x12\x0e\n\nPHILOSOPHY\x10\x02\x12\x0b\n\x07HISTORY\x10\x03\x12\x15\n\x11\x46ICTION_ADVENTURE\x10\x04\x42\x07\n\x05_isbnB\x08\n\x06_titleB\t\n\x07_authorB\x08\n\x06_genreB\x0b\n\t_pub_year\"\xdb\x01\n\rInventoryItem\x12\x1d\n\x10inventory_number\x18\x01 \x01(\x05H\x01\x88\x01\x01\x12\x1f\n\x04\x62ook\x18\x05 \x01(\x0b\x32\x0f.inventory.BookH\x00\x12\x39\n\x06status\x18\x02 \x01(\x0e\x32$.inventory.InventoryItem.IssueStatusH\x02\x88\x01\x01\"\'\n\x0bIssueStatus\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x42\x06\n\x04itemB\x13\n\x11_inventory_numberB\t\n\x07_statusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_entities_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSESTATUS._serialized_start=64
  _RESPONSESTATUS._serialized_end=150
  _BOOK._serialized_start=153
  _BOOK._serialized_end=443
  _BOOK_GENRE._serialized_start=287
  _BOOK_GENRE._serialized_end=390
  _INVENTORYITEM._serialized_start=446
  _INVENTORYITEM._serialized_end=665
  _INVENTORYITEM_ISSUESTATUS._serialized_start=586
  _INVENTORYITEM_ISSUESTATUS._serialized_end=625
# @@protoc_insertion_point(module_scope)
